# Generated by Django 6.0.1 on 2026-02-14 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_bus_bus_name_remove_route_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='capacity',
            new_name='total_seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
